// Color theme definitions
export interface ColorTheme {
  name: string;
  tags?: string[];
  light: {
    primary: string;
    primaryShadow: string;
    accent: string;
    accentShadow: string;
    background: string;
    cardBackground: string;
    text: string;
    extra: string;
    h1Color: 'primary' | 'accent' | 'text';
    h2Color: 'primary' | 'accent' | 'text';
    h3Color: 'primary' | 'accent' | 'text';
  };
  dark: {
    primary: string;
    primaryShadow: string;
    accent: string;
    accentShadow: string;
    background: string;
    cardBackground: string;
    text: string;
    extra: string;
    h1Color: 'primary' | 'accent' | 'text';
    h2Color: 'primary' | 'accent' | 'text';
    h3Color: 'primary' | 'accent' | 'text';
  };
}

export const colorThemes: ColorTheme[] = [
  {
    name: 'Ocean Blue',
    tags: ['corporate'],
    light: {
      primary: '#0066CC',
      primaryShadow: '#004C99',
      accent: '#FF6B35',
      accentShadow: '#CC5529',
      background: '#FFFFFF',
      cardBackground: '#F5F5F5',
      text: '#333333',
      extra: '#00D4FF',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
    dark: {
      primary: '#3399FF',
      primaryShadow: '#0066CC',
      accent: '#FF8C5A',
      accentShadow: '#FF6B35',
      background: '#1A1A1A',
      cardBackground: '#2A2A2A',
      text: '#E0E0E0',
      extra: '#00D4FF',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
  },
  {
    name: 'Forest Green',
    light: {
      primary: '#2D6A4F',
      primaryShadow: '#1B4332',
      accent: '#D4A373',
      accentShadow: '#B8865B',
      background: '#FEFEFE',
      cardBackground: '#F1FAEE',
      text: '#1B4332',
      extra: '#52B788',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'primary',
    },
    dark: {
      primary: '#52B788',
      primaryShadow: '#2D6A4F',
      accent: '#E9C46A',
      accentShadow: '#D4A373',
      background: '#1B1B1B',
      cardBackground: '#2D3E2F',
      text: '#E8F3E8',
      extra: '#95D5B2',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'primary',
    },
  },
  {
    name: 'Sunset Pink',
    tags: ['funky'],
    light: {
      primary: '#E63946',
      primaryShadow: '#C5303D',
      accent: '#FFB703',
      accentShadow: '#DC9F02',
      background: '#FFFFFF',
      cardBackground: '#FFF3F3',
      text: '#2B2D42',
      extra: '#FB5607',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'accent',
    },
    dark: {
      primary: '#FF5A67',
      primaryShadow: '#E63946',
      accent: '#FFD60A',
      accentShadow: '#FFB703',
      background: '#1A1A2E',
      cardBackground: '#2B2D42',
      text: '#EDF2F4',
      extra: '#FB5607',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'accent',
    },
  },
  {
    name: 'Purple Dream',
    tags: ['funky'],
    light: {
      primary: '#7209B7',
      primaryShadow: '#560BAD',
      accent: '#F72585',
      accentShadow: '#D90368',
      background: '#FFFFFF',
      cardBackground: '#F8F0FF',
      text: '#2B2D42',
      extra: '#4CC9F0',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
    dark: {
      primary: '#B388FF',
      primaryShadow: '#7209B7',
      accent: '#FF4DA6',
      accentShadow: '#F72585',
      background: '#1A1A2E',
      cardBackground: '#2D2A3E',
      text: '#E0E0E0',
      extra: '#4CC9F0',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
  },
  {
    name: 'Monochrome',
    tags: ['corporate'],
    light: {
      primary: '#212529',
      primaryShadow: '#000000',
      accent: '#6C757D',
      accentShadow: '#495057',
      background: '#FFFFFF',
      cardBackground: '#F8F9FA',
      text: '#212529',
      extra: '#ADB5BD',
      h1Color: 'primary',
      h2Color: 'text',
      h3Color: 'accent',
    },
    dark: {
      primary: '#F8F9FA',
      primaryShadow: '#DEE2E6',
      accent: '#ADB5BD',
      accentShadow: '#6C757D',
      background: '#212529',
      cardBackground: '#343A40',
      text: '#F8F9FA',
      extra: '#6C757D',
      h1Color: 'primary',
      h2Color: 'text',
      h3Color: 'accent',
    },
  },
  {
    name: 'Midnight Blue',
    tags: ['corporate'],
    light: {
      primary: '#1E3A8A',
      primaryShadow: '#1E3A8A',
      accent: '#F59E0B',
      accentShadow: '#D97706',
      background: '#FFFFFF',
      cardBackground: '#F0F9FF',
      text: '#1F2937',
      extra: '#60A5FA',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
    dark: {
      primary: '#60A5FA',
      primaryShadow: '#3B82F6',
      accent: '#FBBF24',
      accentShadow: '#F59E0B',
      background: '#0F172A',
      cardBackground: '#1E293B',
      text: '#F1F5F9',
      extra: '#93C5FD',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
  },
  {
    name: 'Coral Reef',
    tags: ['funky'],
    light: {
      primary: '#FF6B6B',
      primaryShadow: '#E85D5D',
      accent: '#4ECDC4',
      accentShadow: '#45B8B0',
      background: '#FFFBF7',
      cardBackground: '#FFF5F0',
      text: '#2C3E50',
      extra: '#FFE66D',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'accent',
    },
    dark: {
      primary: '#FF8787',
      primaryShadow: '#FF6B6B',
      accent: '#6EDDD6',
      accentShadow: '#4ECDC4',
      background: '#1A1A2E',
      cardBackground: '#16213E',
      text: '#F0F0F0',
      extra: '#FFE66D',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'accent',
    },
  },
  {
    name: 'Lavender Fields',
    light: {
      primary: '#9D84B7',
      primaryShadow: '#8971A6',
      accent: '#C8A2C8',
      accentShadow: '#B88FB8',
      background: '#FFFFFF',
      cardBackground: '#F9F5FF',
      text: '#3D3D3D',
      extra: '#E0BBE4',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
    dark: {
      primary: '#C8A2C8',
      primaryShadow: '#9D84B7',
      accent: '#E0BBE4',
      accentShadow: '#C8A2C8',
      background: '#1A1625',
      cardBackground: '#2A2438',
      text: '#E8E4F3',
      extra: '#D4A5D4',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
  },
  {
    name: 'Autumn Harvest',
    light: {
      primary: '#C2410C',
      primaryShadow: '#9A3412',
      accent: '#F59E0B',
      accentShadow: '#D97706',
      background: '#FFFBEB',
      cardBackground: '#FEF3C7',
      text: '#451A03',
      extra: '#FB923C',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
    dark: {
      primary: '#FB923C',
      primaryShadow: '#F97316',
      accent: '#FCD34D',
      accentShadow: '#FBBF24',
      background: '#1C1917',
      cardBackground: '#292524',
      text: '#FEF3C7',
      extra: '#FDBA74',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
  },
  {
    name: 'Mint Fresh',
    light: {
      primary: '#10B981',
      primaryShadow: '#059669',
      accent: '#06B6D4',
      accentShadow: '#0891B2',
      background: '#FFFFFF',
      cardBackground: '#F0FDF4',
      text: '#064E3B',
      extra: '#6EE7B7',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
    dark: {
      primary: '#34D399',
      primaryShadow: '#10B981',
      accent: '#22D3EE',
      accentShadow: '#06B6D4',
      background: '#0F1419',
      cardBackground: '#1C2128',
      text: '#D1FAE5',
      extra: '#6EE7B7',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
  },
  {
    name: 'Cherry Blossom',
    tags: ['funky'],
    light: {
      primary: '#EC4899',
      primaryShadow: '#DB2777',
      accent: '#F472B6',
      accentShadow: '#EC4899',
      background: '#FFF5F7',
      cardBackground: '#FCE7F3',
      text: '#831843',
      extra: '#F9A8D4',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
    dark: {
      primary: '#F9A8D4',
      primaryShadow: '#F472B6',
      accent: '#FBCFE8',
      accentShadow: '#F9A8D4',
      background: '#1F1720',
      cardBackground: '#2D1B28',
      text: '#FCE7F3',
      extra: '#FBD5E9',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
  },
  {
    name: 'Deep Sea',
    tags: ['corporate'],
    light: {
      primary: '#0E7490',
      primaryShadow: '#155E75',
      accent: '#06B6D4',
      accentShadow: '#0891B2',
      background: '#F0FDFA',
      cardBackground: '#CCFBF1',
      text: '#134E4A',
      extra: '#5EEAD4',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
    dark: {
      primary: '#22D3EE',
      primaryShadow: '#06B6D4',
      accent: '#67E8F9',
      accentShadow: '#22D3EE',
      background: '#0C1821',
      cardBackground: '#1B2838',
      text: '#CFFAFE',
      extra: '#A5F3FC',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'accent',
    },
  },
  {
    name: 'Slate & Gold',
    tags: ['corporate'],
    light: {
      primary: '#475569',
      primaryShadow: '#334155',
      accent: '#F59E0B',
      accentShadow: '#D97706',
      background: '#FFFFFF',
      cardBackground: '#F8FAFC',
      text: '#1E293B',
      extra: '#94A3B8',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'text',
    },
    dark: {
      primary: '#94A3B8',
      primaryShadow: '#64748B',
      accent: '#FBBF24',
      accentShadow: '#F59E0B',
      background: '#0F172A',
      cardBackground: '#1E293B',
      text: '#F1F5F9',
      extra: '#CBD5E1',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'text',
    },
  },
  {
    name: 'Crimson & Cream',
    tags: ['funky'],
    light: {
      primary: '#BE123C',
      primaryShadow: '#9F1239',
      accent: '#FDE68A',
      accentShadow: '#FCD34D',
      background: '#FFFBEB',
      cardBackground: '#FEF3C7',
      text: '#450A0A',
      extra: '#FCA5A5',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'text',
    },
    dark: {
      primary: '#FDA4AF',
      primaryShadow: '#FB7185',
      accent: '#FEF08A',
      accentShadow: '#FDE047',
      background: '#1C1917',
      cardBackground: '#292524',
      text: '#FFF1F2',
      extra: '#FECACA',
      h1Color: 'primary',
      h2Color: 'primary',
      h3Color: 'text',
    },
  },
  {
    name: 'Emerald City',
    light: {
      primary: '#047857',
      primaryShadow: '#065F46',
      accent: '#84CC16',
      accentShadow: '#65A30D',
      background: '#F7FEF0',
      cardBackground: '#ECFCCB',
      text: '#14532D',
      extra: '#34D399',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
    dark: {
      primary: '#34D399',
      primaryShadow: '#10B981',
      accent: '#BEF264',
      accentShadow: '#A3E635',
      background: '#0A1F14',
      cardBackground: '#14532D',
      text: '#D1FAE5',
      extra: '#6EE7B7',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
  },
  {
    name: 'Royal Purple',
    tags: ['funky'],
    light: {
      primary: '#6B21A8',
      primaryShadow: '#581C87',
      accent: '#A855F7',
      accentShadow: '#9333EA',
      background: '#FAF5FF',
      cardBackground: '#F3E8FF',
      text: '#3B0764',
      extra: '#C084FC',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
    dark: {
      primary: '#C084FC',
      primaryShadow: '#A855F7',
      accent: '#D8B4FE',
      accentShadow: '#C084FC',
      background: '#1E1228',
      cardBackground: '#2E1A47',
      text: '#F3E8FF',
      extra: '#E9D5FF',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
  },
  {
    name: 'Tangerine Dream',
    tags: ['funky'],
    light: {
      primary: '#EA580C',
      primaryShadow: '#C2410C',
      accent: '#FBBF24',
      accentShadow: '#F59E0B',
      background: '#FFFBEB',
      cardBackground: '#FEF3C7',
      text: '#78350F',
      extra: '#FB923C',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
    dark: {
      primary: '#FB923C',
      primaryShadow: '#F97316',
      accent: '#FDE047',
      accentShadow: '#FACC15',
      background: '#1C1410',
      cardBackground: '#292524',
      text: '#FEF3C7',
      extra: '#FDBA74',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
  },
  {
    name: 'Arctic Ice',
    tags: ['corporate'],
    light: {
      primary: '#0369A1',
      primaryShadow: '#075985',
      accent: '#67E8F9',
      accentShadow: '#22D3EE',
      background: '#F0F9FF',
      cardBackground: '#E0F2FE',
      text: '#0C4A6E',
      extra: '#BAE6FD',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
    dark: {
      primary: '#7DD3FC',
      primaryShadow: '#38BDF8',
      accent: '#A5F3FC',
      accentShadow: '#67E8F9',
      background: '#0A1929',
      cardBackground: '#1E293B',
      text: '#E0F2FE',
      extra: '#BAE6FD',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
  },
  {
    name: 'Berry Blast',
    tags: ['funky'],
    light: {
      primary: '#BE185D',
      primaryShadow: '#9F1239',
      accent: '#7C3AED',
      accentShadow: '#6D28D9',
      background: '#FFF1F2',
      cardBackground: '#FCE7F3',
      text: '#4A044E',
      extra: '#F472B6',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
    dark: {
      primary: '#F472B6',
      primaryShadow: '#EC4899',
      accent: '#A78BFA',
      accentShadow: '#8B5CF6',
      background: '#1F1129',
      cardBackground: '#2D1B3D',
      text: '#FCE7F3',
      extra: '#F9A8D4',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'primary',
    },
  },
  {
    name: 'Coffee & Cream',
    tags: ['corporate'],
    light: {
      primary: '#78350F',
      primaryShadow: '#451A03',
      accent: '#A16207',
      accentShadow: '#854D0E',
      background: '#FFFBEB',
      cardBackground: '#FEF3C7',
      text: '#292524',
      extra: '#D97706',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'text',
    },
    dark: {
      primary: '#FCD34D',
      primaryShadow: '#FBBF24',
      accent: '#FDE68A',
      accentShadow: '#FCD34D',
      background: '#1C1917',
      cardBackground: '#292524',
      text: '#FEF3C7',
      extra: '#F59E0B',
      h1Color: 'primary',
      h2Color: 'accent',
      h3Color: 'text',
    },
  },
];

// Font pairing definitions
export interface FontPairing {
  name: string;
  heading: string;
  headingStyle: string[];
  body: string;
  bodyStyle: string[];
}

export const fontPairings: FontPairing[] = [
  {
    name: 'Inter & Geist',
    heading: 'Inter',
    headingStyle: ['sans'],
    body: 'Geist',
    bodyStyle: ['sans', 'mono'],
  },
  {
    name: 'Playfair Display & Source Sans Pro',
    heading: 'Playfair Display',
    headingStyle: ['serif', 'display'],
    body: 'Source Sans Pro',
    bodyStyle: ['sans'],
  },
  {
    name: 'Montserrat & Open Sans',
    heading: 'Montserrat',
    headingStyle: ['sans', 'display'],
    body: 'Open Sans',
    bodyStyle: ['sans'],
  },
  {
    name: 'Raleway & Lato',
    heading: 'Raleway',
    headingStyle: ['sans', 'display'],
    body: 'Lato',
    bodyStyle: ['sans'],
  },
  {
    name: 'Poppins & Roboto',
    heading: 'Poppins',
    headingStyle: ['sans', 'display'],
    body: 'Roboto',
    bodyStyle: ['sans'],
  },
  {
    name: 'Merriweather & Lora',
    heading: 'Merriweather',
    headingStyle: ['serif'],
    body: 'Lora',
    bodyStyle: ['serif'],
  },
  {
    name: 'Oswald & Nunito',
    heading: 'Oswald',
    headingStyle: ['sans', 'display'],
    body: 'Nunito',
    bodyStyle: ['sans'],
  },
  {
    name: 'Space Grotesk & Space Mono',
    heading: 'Space Grotesk',
    headingStyle: ['sans'],
    body: 'Space Mono',
    bodyStyle: ['mono'],
  },
  {
    name: 'DM Serif Display & DM Sans',
    heading: 'DM Serif Display',
    headingStyle: ['serif', 'display'],
    body: 'DM Sans',
    bodyStyle: ['sans'],
  },
  {
    name: 'Crimson Text & Work Sans',
    heading: 'Crimson Text',
    headingStyle: ['serif'],
    body: 'Work Sans',
    bodyStyle: ['sans'],
  },
  {
    name: 'Abril Fatface & Libre Baskerville',
    heading: 'Abril Fatface',
    headingStyle: ['serif', 'display'],
    body: 'Libre Baskerville',
    bodyStyle: ['serif'],
  },
  {
    name: 'Bebas Neue & Mukta',
    heading: 'Bebas Neue',
    headingStyle: ['sans', 'display'],
    body: 'Mukta',
    bodyStyle: ['sans'],
  },
  {
    name: 'Cormorant Garamond & Proza Libre',
    heading: 'Cormorant Garamond',
    headingStyle: ['serif'],
    body: 'Proza Libre',
    bodyStyle: ['sans'],
  },
  {
    name: 'Josefin Sans & Lato',
    heading: 'Josefin Sans',
    headingStyle: ['sans', 'display'],
    body: 'Lato',
    bodyStyle: ['sans'],
  },
  {
    name: 'Spectral & Karla',
    heading: 'Spectral',
    headingStyle: ['serif'],
    body: 'Karla',
    bodyStyle: ['sans'],
  },
  {
    name: 'Libre Franklin & Libre Baskerville',
    heading: 'Libre Franklin',
    headingStyle: ['sans'],
    body: 'Libre Baskerville',
    bodyStyle: ['serif'],
  },
  {
    name: 'Archivo & Roboto',
    heading: 'Archivo',
    headingStyle: ['sans', 'display'],
    body: 'Roboto',
    bodyStyle: ['sans'],
  },
  {
    name: 'Yeseva One & Josefin Sans',
    heading: 'Yeseva One',
    headingStyle: ['serif', 'display'],
    body: 'Josefin Sans',
    bodyStyle: ['sans'],
  },
  {
    name: 'Arvo & PT Sans',
    heading: 'Arvo',
    headingStyle: ['serif'],
    body: 'PT Sans',
    bodyStyle: ['sans'],
  },
  {
    name: 'Cabin & Cabin',
    heading: 'Cabin',
    headingStyle: ['sans'],
    body: 'Cabin',
    bodyStyle: ['sans'],
  },
  {
    name: 'Rubik & Karla',
    heading: 'Rubik',
    headingStyle: ['sans', 'display'],
    body: 'Karla',
    bodyStyle: ['sans'],
  },
  {
    name: 'Vollkorn & Lato',
    heading: 'Vollkorn',
    headingStyle: ['serif'],
    body: 'Lato',
    bodyStyle: ['sans'],
  },
  {
    name: 'Fjalla One & Noto Sans',
    heading: 'Fjalla One',
    headingStyle: ['sans', 'display'],
    body: 'Noto Sans',
    bodyStyle: ['sans'],
  },
  {
    name: 'Bitter & Raleway',
    heading: 'Bitter',
    headingStyle: ['serif'],
    body: 'Raleway',
    bodyStyle: ['sans'],
  },
  {
    name: 'Cardo & Muli',
    heading: 'Cardo',
    headingStyle: ['serif'],
    body: 'Mulish',
    bodyStyle: ['sans'],
  },
  {
    name: 'Fira Sans & Merriweather',
    heading: 'Fira Sans',
    headingStyle: ['sans'],
    body: 'Merriweather',
    bodyStyle: ['serif'],
  },
  {
    name: 'Outfit & Outfit',
    heading: 'Outfit',
    headingStyle: ['sans'],
    body: 'Outfit',
    bodyStyle: ['sans'],
  },
  {
    name: 'Manrope & Manrope',
    heading: 'Manrope',
    headingStyle: ['sans'],
    body: 'Manrope',
    bodyStyle: ['sans'],
  },
  {
    name: 'Sora & Sora',
    heading: 'Sora',
    headingStyle: ['sans'],
    body: 'Sora',
    bodyStyle: ['sans'],
  },
  {
    name: 'Plus Jakarta Sans & Plus Jakarta Sans',
    heading: 'Plus Jakarta Sans',
    headingStyle: ['sans'],
    body: 'Plus Jakarta Sans',
    bodyStyle: ['sans'],
  },
];
